// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: enum.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_enum_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_enum_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_enum_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_enum_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_enum_2eproto;
PROTOBUF_NAMESPACE_OPEN
PROTOBUF_NAMESPACE_CLOSE
namespace Protocol {

enum STONE_COLOR : int {
  BLACK = 0,
  WHITE = 1,
  NONE = 2,
  STONE_COLOR_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::min(),
  STONE_COLOR_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::max()
};
bool STONE_COLOR_IsValid(int value);
constexpr STONE_COLOR STONE_COLOR_MIN = BLACK;
constexpr STONE_COLOR STONE_COLOR_MAX = NONE;
constexpr int STONE_COLOR_ARRAYSIZE = STONE_COLOR_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* STONE_COLOR_descriptor();
template<typename T>
inline const std::string& STONE_COLOR_Name(T enum_t_value) {
  static_assert(::std::is_same<T, STONE_COLOR>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function STONE_COLOR_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    STONE_COLOR_descriptor(), enum_t_value);
}
inline bool STONE_COLOR_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, STONE_COLOR* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<STONE_COLOR>(
    STONE_COLOR_descriptor(), name, value);
}
enum GAME_OVER : int {
  WIN = 0,
  LOSE = 1,
  EXIT = 2,
  GAME_OVER_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::min(),
  GAME_OVER_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::max()
};
bool GAME_OVER_IsValid(int value);
constexpr GAME_OVER GAME_OVER_MIN = WIN;
constexpr GAME_OVER GAME_OVER_MAX = EXIT;
constexpr int GAME_OVER_ARRAYSIZE = GAME_OVER_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* GAME_OVER_descriptor();
template<typename T>
inline const std::string& GAME_OVER_Name(T enum_t_value) {
  static_assert(::std::is_same<T, GAME_OVER>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function GAME_OVER_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    GAME_OVER_descriptor(), enum_t_value);
}
inline bool GAME_OVER_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, GAME_OVER* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<GAME_OVER>(
    GAME_OVER_descriptor(), name, value);
}
// ===================================================================


// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace Protocol

PROTOBUF_NAMESPACE_OPEN

template <> struct is_proto_enum< ::Protocol::STONE_COLOR> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::Protocol::STONE_COLOR>() {
  return ::Protocol::STONE_COLOR_descriptor();
}
template <> struct is_proto_enum< ::Protocol::GAME_OVER> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::Protocol::GAME_OVER>() {
  return ::Protocol::GAME_OVER_descriptor();
}

PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_enum_2eproto
